apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: partition
spec:
  action: partition
  mode: all
  selector:
    namespaces: [REPLACE]
    labelSelectors:
      statefulset.kubernetes.io/pod-name: REPLACE
  direction: both
  target:
    mode: all
    selector:
      namespaces: [REPLACE]
      labelSelectors:
        statefulset.kubernetes.io/pod-name: REPLACE