apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: REPLACE
  namespace: chaos-mesh
spec:
  action: pod-failure
  mode: one
  duration: 10m
  selector:
    namespaces: [REPLACE]
    labelSelectors:
      statefulset.kubernetes.io/pod-name: REPLACE